// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2F7_gOdZ4eLCxHMowyBu2VlzAPtfkhUo',
    appId: '1:891918304232:web:b82c0a20a7b018c919da5d',
    messagingSenderId: '891918304232',
    projectId: 'kaushikcloud-c65b3',
    authDomain: 'kaushikcloud-c65b3.firebaseapp.com',
    storageBucket: 'kaushikcloud-c65b3.firebasestorage.app',
    measurementId: 'G-7YDC7SFDY3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvf2RTXy9ad0vzGs2zJj-BKdmlYjvNImg',
    appId: '1:891918304232:android:5004b93b0a9aa5c819da5d',
    messagingSenderId: '891918304232',
    projectId: 'kaushikcloud-c65b3',
    storageBucket: 'kaushikcloud-c65b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIc9XmXUnINOo9X2kzlbuU5mfda10uL0Y',
    appId: '1:891918304232:ios:d6c3ab6cb071a02f19da5d',
    messagingSenderId: '891918304232',
    projectId: 'kaushikcloud-c65b3',
    storageBucket: 'kaushikcloud-c65b3.firebasestorage.app',
    iosBundleId: 'com.example.kau',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIc9XmXUnINOo9X2kzlbuU5mfda10uL0Y',
    appId: '1:891918304232:ios:d6c3ab6cb071a02f19da5d',
    messagingSenderId: '891918304232',
    projectId: 'kaushikcloud-c65b3',
    storageBucket: 'kaushikcloud-c65b3.firebasestorage.app',
    iosBundleId: 'com.example.kau',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2F7_gOdZ4eLCxHMowyBu2VlzAPtfkhUo',
    appId: '1:891918304232:web:d315b6b0afb868b119da5d',
    messagingSenderId: '891918304232',
    projectId: 'kaushikcloud-c65b3',
    authDomain: 'kaushikcloud-c65b3.firebaseapp.com',
    storageBucket: 'kaushikcloud-c65b3.firebasestorage.app',
    measurementId: 'G-2L7YXLF3RW',
  );
}
